### ISSUE TITLE
server browser without devexpress? 

### ISSUE THREAD

**Issue by exelv1** [PredatH0r/SteamServerBrowser#1]
im VERY INTERESTED IN WHAT YOU HAVE MADE i run a esports company and would like to see if you could interrogate this in a environment with a webpage our site is gesn.net  we plan to have quake csgo unreal tourny and few mobas we are also doing the  very first esports broadcasting company my email is mrhdr405@gmail.com ping me also u member paul?  http://paulbaker.net/work.html  im sure you know him ahahah

**Comment by PredatH0r** [comment]
Thanks for your interest!
The GUI part of my server browser only works under .NET/Windows and would be too much effort for me to rewrite for a web based UI. The whole logic to query servers is now in separated out and could be reused for such a project.
My browser works with the upcoming "Steam exlcusive" version of QuakeLive, but UT4 uses it's own proprietary protocol and is not compatible. I'm not sure about CS:GO, becasue it "should" be supported, but I can't find any servers. Maybe this game is using a different master server. And I no idea if any Mobas use the Steam/Valve server query protocol.
The guy(s) at http://www.serverbrowser.com/ have something that might be more like what you're looking for.

**Comment by exelv1** [comment]
no i want it on client end actualy i was just curious can you shoot me a email or give me a call 7036082053 so we can talk a bit about some of ur work.

**Comment by exelv1** [comment]
any way we can have a convo on gchat / phone? mrhdr405@gmail.com 7036082053
