### ISSUE TITLE
empty server list

### ISSUE THREAD

**Issue by atomGit** [PredatH0r/SteamServerBrowser#11]
v1.12.2

was fooling around with selecting skins, then clicked the button to use the default and the skin did not reset so i restarted the program and now the server list is empty

i looked for where the it is storing settings so i could reset them, but couldn't find where they are stored

http://s6.postimg.org/vymjq3nvl/screenshot_183.png

**Comment by atomGit** [comment]
appears this may have been due to the max packets thingy you mentioned here:
https://github.com/PredatH0r/SteamServerBrowser/issues/4

the list is populated now

**Comment by PredatH0r** [comment]
The ServerBrowser uses the default .NET application setting storage system.
If you open a File Explorer and copy "%appdata%\..\Local\ServerBrowser" in the folder field, you'll see directories for each version, which contain the settings files.
