### ISSUE TITLE
filtering enhancement 

### ISSUE THREAD

**Issue by atomGit** [PredatH0r/SteamServerBrowser#12]
for the quick-filtering row on top of the server list, i think it would be better to parse the entire name for the string entered - in other words, the default should be 'contains' instead of 'equals' - at least for all columns that contain text strings

example - if i want to find all servers containing 'abc' in the name, none would be found if the name doesn't begin with 'abc'

i'll stop spamming you now :)

**Comment by PredatH0r** [comment]
implemented in 1.16
