### ISSUE TITLE
pmove_ cvars

### ISSUE THREAD

**Issue by Melodeiro** [PredatH0r/SteamServerBrowser#15]
Would be great if this tool will show pmove_ cvars in "rules" tab. So we can sure if it is a classic, PQL or new QL ruleset server.

**Comment by PredatH0r** [comment]
Unfortunately that is not possible. 
I am showing all the information that the game server returns. Quake Live only exposes a subset of server cvars through the server browser protocol. I have asked the QL devs many times to add certain fields to no avail.

**Comment by Melodeiro** [comment]
Using /cvarlist is not allowed by that protocol, right? Dont even sure if it contains pmove_ cvars, because new quake console shows way too small amount of lines.

**Comment by PredatH0r** [comment]
The server browser protocol is very primitive. There are only 3 queries, A2S_INFO (basic server information), A2S_PLAYERS (list of players) and A2S_RULES. No options/parameters for these queries. These queries work for all games which support the Steam/Valve master server infrastructure.

If you have RCON access to a Quake Live server, you can get more information through that. But for 99.9% of server you don't have that access.
