### ISSUE TITLE
Manual adding servers

### ISSUE THREAD

**Issue by Melodeiro** [PredatH0r/SteamServerBrowser#16]
Would be nice to see manual adding of servers with ip:port to favorites. Or i just don't found this feature? Quake Live servers.

**Comment by PredatH0r** [comment]
With the yellow "+" button you can add a manual server list, add your servers there and then mark them as favorites.
You can't manually add servers to lists which are retrieved from the steam master server.

**Comment by Melodeiro** [comment]
Thats ok, thanks!
