### ISSUE TITLE
Socket exception

### ISSUE THREAD

**Issue by sampeto** [PredatH0r/SteamServerBrowser#2]
It's something minor, but I thought I'd mention it. Clicking "Show Options" and then the + button next to "Game server: " without entering any text in the field results in a socket exception, and the program crashing.

**Comment by PredatH0r** [comment]
Thx for the feedback. This is now fixed in 1.11. Empty values are ignored, and if a host name is provided, only it's IPv4 address is used. (The crash was caused because the blank name returned a special IPv6 address)
