### ISSUE TITLE
L4D2 Master server

### ISSUE THREAD

**Issue by heretic43** [PredatH0r/SteamServerBrowser#22]
I am in China, want to play on China servers, Master server is 115.238.147.238:27011, but it does not work, always get valve servers

**Comment by PredatH0r** [comment]
I re-added support for UDP based master server queries.
It looks like Valve is also supporting the protocol again, after they had turned it off in the past.
However the serverver:port you mentioned does not return any data to me.

Can you try out this version: https://github.com/PredatH0r/SteamServerBrowser/releases/tag/v2.44
with that server? In the "Game" field I tried "550" - which is the steam app ID for L4D2.

**Comment by heretic43** [comment]
Maybe I was wrong, the MasterServer is found in the cracked version of the game
![2017-06-15 15_22_08-rev ini - notepad2-mod](https://user-images.githubusercontent.com/29085894/27169906-81fbf212-51de-11e7-9f02-31945c3a2976.png)
