### ISSUE TITLE
Not updating after 2.42

### ISSUE THREAD

**Issue by josestefan** [PredatH0r/SteamServerBrowser#23]
I downloaded the Steam Server Browser thru the steam workshop for quake live.

It always updated fine, but now it's stuck at this revision. I see there are new releases on the website. 

I tried unsubscribing / re-subscribing to the workshop item.

**Comment by PredatH0r** [comment]
workshop is now updated with the latest version.

**Comment by josestefan** [comment]
Confirmed Fixed.
