### ISSUE TITLE
Filter by server rule

### ISSUE THREAD

**Issue by sampeto** [PredatH0r/SteamServerBrowser#3]
Would it be possible to implement a feature to filter by a specified server rule? For example, only show servers with sv_cheats set to 1.

**Comment by PredatH0r** [comment]
The Steam master servers don't support server-side filtering for rules, but v1.11 now allows you to add  client-side filter for it:

Right click a rule (make sure that the cell editor is not open - press ESC to close it if necessary) and select "Add text column ..." or "Add numeric column ..." from the context menu.
Once you have the column in the Servers table, you can use it to apply client side filters.

**Comment by sampeto** [comment]
Thanks, this works perfectly!
