### ISSUE TITLE
Request to Add Customizable Result Limit Option

### ISSUE THREAD

**Issue by BodenMcHale** [PredatH0r/SteamServerBrowser#36]
Could you please consider adding an option to customize the "Limit Results" value? 

I'm using your software to search for active servers for 7 Days to Die, but the current limit of 6,930 results falls short of the total number of servers available (over 8,000).

I would be very grateful for any assistance in resolving this issue.

**Comment by PredatH0r** [comment]
6930 is a historic limit when using UDP queries to the master server, which then starts throttling/blocking any further requests for a minute. When using the Steam Web API you can actually get more that that.

I uploaded a modified build to https://chansort.com/SteamServerBrowser-2.63.zip

**Comment by BodenMcHale** [comment]
Thank you so much! I appreciate it greatly.
