### ISSUE TITLE
apply filters without refresh

### ISSUE THREAD

**Issue by atomGit** [PredatH0r/SteamServerBrowser#4]
hi!
i can't believe that this is the only HL2/Steam server browser that i've found that supports CS:GO (not a fan of the newer HLSW browser) - seems very odd, but a HUGE thanks for your work!!!

anyway, i humbly ask that you consider applying filters (map, include, exclude) in real-time as they are keyed in without refreshing the whole list

v1.12.2

**Comment by PredatH0r** [comment]
You already can.
The empty row on top of the table is a search/filter row. you can use an asterisk (*) as a placeholder for simple search criteria. e.g. in the map column "*ust*" to search for everything that has "ust" in it.
For more complex filters you can open the filter editor through the link in the options area.

The map/include/exclude filters in the top area are server-side, meaning that they are sent to Valve and Valve already narrows down the server list. Valve limits each IP address to only receive a maximum of 50 packets per minute, which corresponds to about 8000 servers per minute. If you get that many, you have to wait a minute before you get any further replies from Valve.
