### ISSUE TITLE
RCON ???

### ISSUE THREAD

**Issue by atomGit** [PredatH0r/SteamServerBrowser#6]
i don't know what you may have in store for your browser down the road

do you plan on supporting RCON for HL2/CS servers?

**Comment by PredatH0r** [comment]
I started to implement RCON for Quake Live (which uses a different protocol than the Source Engine games), but when the UI for that is in place, it should be simple to add RCON for Source too.
The library I'm using to query the servers already has support for it.

**Comment by LuaTenshi** [comment]
What's the status on this issue?

**Comment by PredatH0r** [comment]
I'm sorry, but I had to cancel my plans to add RCON support.
I have no personal use for it and no longer the spare time to add it just for fun.

**Comment by LuaTenshi** [comment]
Thank you for replying so quickly, was simply curious on the status of the
issue since it wasn't closed.
