### ISSUE TITLE
disable auto-refresh when interval is '0'

### ISSUE THREAD

**Issue by atomGit** [PredatH0r/SteamServerBrowser#7]
v1.12.2
title explains it i think - it appears that even when the auto-refresh interval is '0' that it still auto-refreshes

might also suggest renaming 'reload servers' to simply 'refresh'

**Comment by PredatH0r** [comment]
I checked the code... when you change the refresh interval, it stops the current timer and only if the value is > 0 it starts a new timer.

Reload/Refresh... I know it's confusing and I wish I had better names for it. 
"Reload servers" sends a new query with the server-side filters to the Valve master server and the browser receives a new list of servers.
"Refresh" is not querying the master server, but only updates the status of the already known game servers.

**Comment by atomGit** [comment]
ok, if i understand you correctly there is apparently no way to refresh the list manually without reloading it (absent clicking on every item)

if that's the case, then yes, i'd think that there should be reload and refresh buttons - probably with descriptive tool-tips

**Comment by PredatH0r** [comment]
"Quick Refresh" button was added in 1.13 to update current game server information without loading a new server list from the master server.
